### ISSUE TITLE
Spring Yard Checklist

### ISSUE THREAD

**Issue by shayfrendt** [shayfrendt/house#21]
### March
- [x] Clean gutters
- [ ] Trim crape myrtles (1 to 5 main chutes)
- [ ] Trim other shrubs
- [x] Paint mailbox as needed
- [ ] Till driveway flower beds
- [x] Rake leaves and junk in yard (dethatching)
- [x] Examine drainage and yard puddles
- [x] Test sprinkler system
- [ ] Pressure wash sidewalk, driveway, front door, back deck
- [x] Start up lawn mower
- [ ] Change oil in lawn mower
- [x] Start weed whacker
- [x] Inspect weed whacker air filter
- [x] Start leaf blower
- [x] Inspect leaf blower air filter
- [ ] Purchase pH testing kit
- [ ] Run pH tests on lawn
- [ ] Rent an aerator
- [ ] Aerate the lawn
- [ ] Apply pre-emergent herbicide for crab grass
- [x] Fire up and clean the grill
- [x] Inspect propane tanks for grill
### April
- [ ] Fertilize lawn
- [ ] Lime to raise pH, sulfur to lower pH as appropriate
